[tool.black]
line-length = 99

# includes the data_sources files
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["ngiab_data_preprocess"]
namespaces = true
exclude = ["tests*"]

[project]
name = "ngiab_data_preprocess"
version = "0.0.1"
authors = [{ name = "Josh Cunningham", email = "josh.cu@gmail.com" }]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[build-system]
# scm adds files tracked by git to the package
requires = ["setuptools>=69.0", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"
